apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app
  labels:
    app: static-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web-app
  template:
    metadata:
      labels:
        app: static-web-app
    spec:
      containers:
      - name: static-web-app
        image: static-web-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-service
spec:
  type: LoadBalancer
  selector:
    app: static-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
